### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by AnavrinApps** [victor369basu/Real-time-stock-market-prediction#2]
Can you please make a video tutorial as to how to run this project?

**Comment by victor369basu** [comment]
set the mongodb configuration wrt to ur mongo db database account, and run the command serially as I have written in the readme file
I am not planning to make a video on it right now. But,  if you have any query you could mail me regarding that

**Comment by AnavrinApps** [comment]
Hey! So i installed all the requirements. After which I ran zookeeper & kafka. When I run the node producer.js I get - 

```
internal/modules/cjs/loader.js:267
    throw e;
    ^

SyntaxError: Error parsing /Users/sanchez/Desktop/Real-time-stock-market-prediction-master/package.json: Unexpected token } in JSON at position 742
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:254:20)
    at readPackageScope (internal/modules/cjs/loader.js:279:19)
    at shouldUseESMLoader (internal/modules/run_main.js:36:15)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:24)
    at internal/main/run_main_module.js:17:47 {
  path: '/Users/sanchez/Desktop/Real-time-stock-market-prediction-master/package.json'
}
```
I'm new to programming, so I'd really appreciate your help. Thanks a lot.

**Comment by victor369basu** [comment]
I think this is an error related to an extra or missing bracket in the code. Could please check it once and update me..

**Comment by victor369basu** [comment]
I have corrected the syntax error at Package.json, it would work perfectly fine from now on..
