### ISSUE TITLE
Would like to create the frontend with React

### ISSUE THREAD

**Issue by monizb** [victor369basu/Real-time-stock-market-prediction#4]
Hi,
Im a full stack dev and I'm interested in the project, I would like to create the frontend with react, let me know what you think

**Comment by monizb** [comment]
How about we integrate this with Alpaca Paper Trading API https://alpaca.markets/docs/trading-on-alpaca/paper-trading/ and test it out 😁

**Comment by victor369basu** [comment]
Yes, you can create an app on this, I would be very happy to see it. It would be very generous of you if you mention my work in the credits.
